[build]
  base = "frontend"
  command = "bash build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://riskworks.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
