"""create_snapshots_table

Revision ID: 30e9d7b6b5ad
Revises: 5c9e8a43fc00
Create Date: 2025-09-07 08:59:17.139100

"""
from alembic import op
import sqlalchemy as sa

revision = '30e9d7b6b5ad'
down_revision = '5c9e8a43fc00'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('snapshots',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=255), nullable=False),
	sa.Column('description', sa.Text(), nullable=True),
	sa.Column('risk_data', sa.JSON(), nullable=False),
	sa.Column('action_items_data', sa.JSON(), nullable=True),
	sa.Column('created_at', sa.DateTime(), nullable=False),
	sa.Column('created_by', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_snapshots_created_by'), 'snapshots', ['created_by'], unique=False)
	op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
	op.drop_index(op.f('ix_snapshots_created_by'), table_name='snapshots')
	op.drop_table('snapshots')
	# ### end Alembic commands ###


