"""make_legacy_fields_nullable

Revision ID: 54557e53a28b
Revises: 30e9d7b6b5ad
Create Date: 2025-09-07 09:34:01.546877

"""
from alembic import op
import sqlalchemy as sa

revision = '54557e53a28b'
down_revision = '30e9d7b6b5ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	# Make legacy fields nullable
	op.alter_column('risks', 'severity',
					existing_type=sa.INTEGER(),
					nullable=True)
	op.alter_column('risks', 'impact',
					existing_type=sa.INTEGER(),
					nullable=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	# Revert legacy fields to not nullable
	op.alter_column('risks', 'severity',
					existing_type=sa.INTEGER(),
					nullable=False)
	op.alter_column('risks', 'impact',
					existing_type=sa.INTEGER(),
					nullable=True)
	# ### end Alembic commands ###


