"""remove_legacy_fields_from_risks

Revision ID: 9a722c790bba
Revises: 54557e53a28b
Create Date: 2025-09-07 11:47:24.974720

"""
from alembic import op
import sqlalchemy as sa

revision = '9a722c790bba'
down_revision = '54557e53a28b'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	# Remove legacy fields from risks table
	op.drop_column('risks', 'title')
	op.drop_column('risks', 'description')
	op.drop_column('risks', 'likelihood')
	op.drop_column('risks', 'severity')
	op.drop_column('risks', 'department')
	op.drop_column('risks', 'location')
	op.drop_column('risks', 'root_cause')
	op.drop_column('risks', 'mitigation_strategy')
	op.drop_column('risks', 'contingency_plan')
	op.drop_column('risks', 'target_date')
	op.drop_column('risks', 'review_date')
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	# Re-add legacy fields to risks table
	op.add_column('risks', sa.Column('title', sa.String(length=255), nullable=True))
	op.add_column('risks', sa.Column('description', sa.Text(), nullable=True))
	op.add_column('risks', sa.Column('likelihood', sa.Integer(), nullable=True))
	op.add_column('risks', sa.Column('severity', sa.Integer(), nullable=True))
	op.add_column('risks', sa.Column('department', sa.String(length=100), nullable=True))
	op.add_column('risks', sa.Column('location', sa.String(length=100), nullable=True))
	op.add_column('risks', sa.Column('root_cause', sa.Text(), nullable=True))
	op.add_column('risks', sa.Column('mitigation_strategy', sa.Text(), nullable=True))
	op.add_column('risks', sa.Column('contingency_plan', sa.Text(), nullable=True))
	op.add_column('risks', sa.Column('target_date', sa.DateTime(), nullable=True))
	op.add_column('risks', sa.Column('review_date', sa.DateTime(), nullable=True))
	# ### end Alembic commands ###


